# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameProtocol.Account.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import GameProtocol.Common_pb2
import GameProtocol.USERDB_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameProtocol.Account.proto',
  package='',
  serialized_pb='\n\x1aGameProtocol.Account.proto\x1a\x19GameProtocol.Common.proto\x1a\x19GameProtocol.USERDB.proto\":\n\x0bRoleSummary\x12\x19\n\x08stRoleID\x18\x01 \x01(\x0b\x32\x07.RoleID\x12\x10\n\x08iWorldID\x18\x02 \x01(\x05\"a\n\x1a\x43reateRole_Account_Request\x12\x0f\n\x07worldID\x18\x01 \x01(\r\x12\x11\n\tuPlatform\x18\x02 \x01(\r\x12\x0b\n\x03uin\x18\x03 \x01(\r\x12\x12\n\nszNickName\x18\x04 \x01(\t\"o\n\x1b\x43reateRole_Account_Response\x12\x0f\n\x07iResult\x18\x01 \x01(\x05\x12\x19\n\x08stRoleID\x18\x02 \x01(\x0b\x32\x07.RoleID\x12\x10\n\x08uWorldID\x18\x03 \x01(\r\x12\x12\n\nszNickName\x18\x04 \x01(\t\"=\n\x18\x41\x63\x63ount_ListZone_Request\x12\x0f\n\x07worldID\x18\x01 \x01(\r\x12\x10\n\x08uISPInfo\x18\x02 \x01(\r\"]\n\x19\x41\x63\x63ount_ListZone_Response\x12\x0f\n\x07iResult\x18\x01 \x01(\x05\x12\x10\n\x08uWorldID\x18\x02 \x01(\r\x12\x1d\n\nstZoneList\x18\x03 \x01(\x0b\x32\t.ZoneList\"7\n\x1a\x44\x65leteRole_Account_Request\x12\x19\n\x08stRoleID\x18\x01 \x01(\x0b\x32\x07.RoleID\"n\n\x1b\x44\x65leteRole_Account_Response\x12\x0f\n\x07iResult\x18\x01 \x01(\x05\x12\x19\n\x08stRoleID\x18\x02 \x01(\x0b\x32\x07.RoleID\x12\x13\n\x0buProfession\x18\x04 \x01(\r\x12\x0e\n\x06uLevel\x18\x06 \x01(\r\"6\n\x18\x41\x63\x63ount_ListRole_Request\x12\x0b\n\x03uin\x18\x01 \x01(\r\x12\r\n\x05world\x18\x02 \x01(\r\"e\n\x19\x41\x63\x63ount_ListRole_Response\x12\x0f\n\x07iResult\x18\x01 \x01(\x05\x12\x0b\n\x03uin\x18\x03 \x01(\r\x12\r\n\x05world\x18\x04 \x01(\r\x12\x1b\n\x05roles\x18\x05 \x03(\x0b\x32\x0c.RoleSummary')




_ROLESUMMARY = _descriptor.Descriptor(
  name='RoleSummary',
  full_name='RoleSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stRoleID', full_name='RoleSummary.stRoleID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iWorldID', full_name='RoleSummary.iWorldID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=142,
)


_CREATEROLE_ACCOUNT_REQUEST = _descriptor.Descriptor(
  name='CreateRole_Account_Request',
  full_name='CreateRole_Account_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldID', full_name='CreateRole_Account_Request.worldID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uPlatform', full_name='CreateRole_Account_Request.uPlatform', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uin', full_name='CreateRole_Account_Request.uin', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='szNickName', full_name='CreateRole_Account_Request.szNickName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=241,
)


_CREATEROLE_ACCOUNT_RESPONSE = _descriptor.Descriptor(
  name='CreateRole_Account_Response',
  full_name='CreateRole_Account_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iResult', full_name='CreateRole_Account_Response.iResult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stRoleID', full_name='CreateRole_Account_Response.stRoleID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uWorldID', full_name='CreateRole_Account_Response.uWorldID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='szNickName', full_name='CreateRole_Account_Response.szNickName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=243,
  serialized_end=354,
)


_ACCOUNT_LISTZONE_REQUEST = _descriptor.Descriptor(
  name='Account_ListZone_Request',
  full_name='Account_ListZone_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldID', full_name='Account_ListZone_Request.worldID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uISPInfo', full_name='Account_ListZone_Request.uISPInfo', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=356,
  serialized_end=417,
)


_ACCOUNT_LISTZONE_RESPONSE = _descriptor.Descriptor(
  name='Account_ListZone_Response',
  full_name='Account_ListZone_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iResult', full_name='Account_ListZone_Response.iResult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uWorldID', full_name='Account_ListZone_Response.uWorldID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stZoneList', full_name='Account_ListZone_Response.stZoneList', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=419,
  serialized_end=512,
)


_DELETEROLE_ACCOUNT_REQUEST = _descriptor.Descriptor(
  name='DeleteRole_Account_Request',
  full_name='DeleteRole_Account_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stRoleID', full_name='DeleteRole_Account_Request.stRoleID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=514,
  serialized_end=569,
)


_DELETEROLE_ACCOUNT_RESPONSE = _descriptor.Descriptor(
  name='DeleteRole_Account_Response',
  full_name='DeleteRole_Account_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iResult', full_name='DeleteRole_Account_Response.iResult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stRoleID', full_name='DeleteRole_Account_Response.stRoleID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uProfession', full_name='DeleteRole_Account_Response.uProfession', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uLevel', full_name='DeleteRole_Account_Response.uLevel', index=3,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=571,
  serialized_end=681,
)


_ACCOUNT_LISTROLE_REQUEST = _descriptor.Descriptor(
  name='Account_ListRole_Request',
  full_name='Account_ListRole_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uin', full_name='Account_ListRole_Request.uin', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world', full_name='Account_ListRole_Request.world', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=683,
  serialized_end=737,
)


_ACCOUNT_LISTROLE_RESPONSE = _descriptor.Descriptor(
  name='Account_ListRole_Response',
  full_name='Account_ListRole_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iResult', full_name='Account_ListRole_Response.iResult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uin', full_name='Account_ListRole_Response.uin', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world', full_name='Account_ListRole_Response.world', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roles', full_name='Account_ListRole_Response.roles', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=739,
  serialized_end=840,
)

_ROLESUMMARY.fields_by_name['stRoleID'].message_type = GameProtocol.Common_pb2._ROLEID
_CREATEROLE_ACCOUNT_RESPONSE.fields_by_name['stRoleID'].message_type = GameProtocol.Common_pb2._ROLEID
_ACCOUNT_LISTZONE_RESPONSE.fields_by_name['stZoneList'].message_type = GameProtocol.Common_pb2._ZONELIST
_DELETEROLE_ACCOUNT_REQUEST.fields_by_name['stRoleID'].message_type = GameProtocol.Common_pb2._ROLEID
_DELETEROLE_ACCOUNT_RESPONSE.fields_by_name['stRoleID'].message_type = GameProtocol.Common_pb2._ROLEID
_ACCOUNT_LISTROLE_RESPONSE.fields_by_name['roles'].message_type = _ROLESUMMARY
DESCRIPTOR.message_types_by_name['RoleSummary'] = _ROLESUMMARY
DESCRIPTOR.message_types_by_name['CreateRole_Account_Request'] = _CREATEROLE_ACCOUNT_REQUEST
DESCRIPTOR.message_types_by_name['CreateRole_Account_Response'] = _CREATEROLE_ACCOUNT_RESPONSE
DESCRIPTOR.message_types_by_name['Account_ListZone_Request'] = _ACCOUNT_LISTZONE_REQUEST
DESCRIPTOR.message_types_by_name['Account_ListZone_Response'] = _ACCOUNT_LISTZONE_RESPONSE
DESCRIPTOR.message_types_by_name['DeleteRole_Account_Request'] = _DELETEROLE_ACCOUNT_REQUEST
DESCRIPTOR.message_types_by_name['DeleteRole_Account_Response'] = _DELETEROLE_ACCOUNT_RESPONSE
DESCRIPTOR.message_types_by_name['Account_ListRole_Request'] = _ACCOUNT_LISTROLE_REQUEST
DESCRIPTOR.message_types_by_name['Account_ListRole_Response'] = _ACCOUNT_LISTROLE_RESPONSE

class RoleSummary(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROLESUMMARY

  # @@protoc_insertion_point(class_scope:RoleSummary)

class CreateRole_Account_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEROLE_ACCOUNT_REQUEST

  # @@protoc_insertion_point(class_scope:CreateRole_Account_Request)

class CreateRole_Account_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEROLE_ACCOUNT_RESPONSE

  # @@protoc_insertion_point(class_scope:CreateRole_Account_Response)

class Account_ListZone_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCOUNT_LISTZONE_REQUEST

  # @@protoc_insertion_point(class_scope:Account_ListZone_Request)

class Account_ListZone_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCOUNT_LISTZONE_RESPONSE

  # @@protoc_insertion_point(class_scope:Account_ListZone_Response)

class DeleteRole_Account_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEROLE_ACCOUNT_REQUEST

  # @@protoc_insertion_point(class_scope:DeleteRole_Account_Request)

class DeleteRole_Account_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEROLE_ACCOUNT_RESPONSE

  # @@protoc_insertion_point(class_scope:DeleteRole_Account_Response)

class Account_ListRole_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCOUNT_LISTROLE_REQUEST

  # @@protoc_insertion_point(class_scope:Account_ListRole_Request)

class Account_ListRole_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCOUNT_LISTROLE_RESPONSE

  # @@protoc_insertion_point(class_scope:Account_ListRole_Response)


# @@protoc_insertion_point(module_scope)
