# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameProtocol.Common.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameProtocol.Common.proto',
  package='',
  serialized_pb='\n\x19GameProtocol.Common.proto\"j\n\x08ZoneInfo\x12\x0f\n\x07uZoneID\x18\x01 \x01(\r\x12\x13\n\x0bstrZoneName\x18\x02 \x01(\t\x12\x12\n\nuZoneState\x18\x03 \x01(\r\x12\x11\n\tstrZoneIP\x18\x04 \x01(\t\x12\x11\n\tuZonePort\x18\x05 \x01(\r\"*\n\x08ZoneList\x12\x1e\n\x0bstZoneInfos\x18\x01 \x03(\x0b\x32\t.ZoneInfo\"$\n\x06RoleID\x12\x0b\n\x03uin\x18\x01 \x01(\r\x12\r\n\x05uiSeq\x18\x02 \x01(\r\"4\n\x14LogoutServer_Request\x12\x0b\n\x03uin\x18\x01 \x01(\r\x12\x0f\n\x07uReason\x18\x02 \x01(\r\"(\n\x15LogoutServer_Response\x12\x0f\n\x07iResult\x18\x01 \x01(\x05\"E\n\x12\x41\x64\x64NewName_Request\x12\x0f\n\x07strName\x18\x01 \x01(\t\x12\r\n\x05iType\x18\x02 \x01(\x05\x12\x0f\n\x07name_id\x18\x03 \x01(\r\"W\n\x13\x41\x64\x64NewName_Response\x12\x0f\n\x07iResult\x18\x01 \x01(\x05\x12\r\n\x05iType\x18\x02 \x01(\x05\x12\x0f\n\x07name_id\x18\x03 \x01(\r\x12\x0f\n\x07strName\x18\x04 \x01(\t\"4\n\x12\x44\x65leteName_Request\x12\x0f\n\x07strName\x18\x01 \x01(\t\x12\r\n\x05iType\x18\x02 \x01(\x05\"&\n\x13\x44\x65leteName_Response\x12\x0f\n\x07iResult\x18\x01 \x01(\x05*v\n\x0f\x43hatChannelType\x12\x18\n\x14\x43HAT_CHANNEL_INVALID\x10\x00\x12\x16\n\x12\x43HAT_CHANNEL_WORLD\x10\x01\x12\x18\n\x14\x43HAT_CHANNEL_PRIVATE\x10\x02\x12\x17\n\x13\x43HAT_CHANNEL_SYSTEM\x10\x03*S\n\nenNameType\x12\x18\n\x14\x45N_NAME_TYPE_INVALID\x10\x00\x12\x15\n\x11\x45N_NAME_TYPE_ROLE\x10\x01\x12\x14\n\x10\x45N_NAME_TYPE_MAX\x10\x02')

_CHATCHANNELTYPE = _descriptor.EnumDescriptor(
  name='ChatChannelType',
  full_name='ChatChannelType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHAT_CHANNEL_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAT_CHANNEL_WORLD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAT_CHANNEL_PRIVATE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAT_CHANNEL_SYSTEM', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=569,
  serialized_end=687,
)

ChatChannelType = enum_type_wrapper.EnumTypeWrapper(_CHATCHANNELTYPE)
_ENNAMETYPE = _descriptor.EnumDescriptor(
  name='enNameType',
  full_name='enNameType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_NAME_TYPE_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_NAME_TYPE_ROLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_NAME_TYPE_MAX', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=689,
  serialized_end=772,
)

enNameType = enum_type_wrapper.EnumTypeWrapper(_ENNAMETYPE)
CHAT_CHANNEL_INVALID = 0
CHAT_CHANNEL_WORLD = 1
CHAT_CHANNEL_PRIVATE = 2
CHAT_CHANNEL_SYSTEM = 3
EN_NAME_TYPE_INVALID = 0
EN_NAME_TYPE_ROLE = 1
EN_NAME_TYPE_MAX = 2



_ZONEINFO = _descriptor.Descriptor(
  name='ZoneInfo',
  full_name='ZoneInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uZoneID', full_name='ZoneInfo.uZoneID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strZoneName', full_name='ZoneInfo.strZoneName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uZoneState', full_name='ZoneInfo.uZoneState', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strZoneIP', full_name='ZoneInfo.strZoneIP', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uZonePort', full_name='ZoneInfo.uZonePort', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=135,
)


_ZONELIST = _descriptor.Descriptor(
  name='ZoneList',
  full_name='ZoneList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stZoneInfos', full_name='ZoneList.stZoneInfos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=137,
  serialized_end=179,
)


_ROLEID = _descriptor.Descriptor(
  name='RoleID',
  full_name='RoleID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uin', full_name='RoleID.uin', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uiSeq', full_name='RoleID.uiSeq', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=181,
  serialized_end=217,
)


_LOGOUTSERVER_REQUEST = _descriptor.Descriptor(
  name='LogoutServer_Request',
  full_name='LogoutServer_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uin', full_name='LogoutServer_Request.uin', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uReason', full_name='LogoutServer_Request.uReason', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=219,
  serialized_end=271,
)


_LOGOUTSERVER_RESPONSE = _descriptor.Descriptor(
  name='LogoutServer_Response',
  full_name='LogoutServer_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iResult', full_name='LogoutServer_Response.iResult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=273,
  serialized_end=313,
)


_ADDNEWNAME_REQUEST = _descriptor.Descriptor(
  name='AddNewName_Request',
  full_name='AddNewName_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strName', full_name='AddNewName_Request.strName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iType', full_name='AddNewName_Request.iType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name_id', full_name='AddNewName_Request.name_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=315,
  serialized_end=384,
)


_ADDNEWNAME_RESPONSE = _descriptor.Descriptor(
  name='AddNewName_Response',
  full_name='AddNewName_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iResult', full_name='AddNewName_Response.iResult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iType', full_name='AddNewName_Response.iType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name_id', full_name='AddNewName_Response.name_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strName', full_name='AddNewName_Response.strName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=386,
  serialized_end=473,
)


_DELETENAME_REQUEST = _descriptor.Descriptor(
  name='DeleteName_Request',
  full_name='DeleteName_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strName', full_name='DeleteName_Request.strName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iType', full_name='DeleteName_Request.iType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=475,
  serialized_end=527,
)


_DELETENAME_RESPONSE = _descriptor.Descriptor(
  name='DeleteName_Response',
  full_name='DeleteName_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iResult', full_name='DeleteName_Response.iResult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=529,
  serialized_end=567,
)

_ZONELIST.fields_by_name['stZoneInfos'].message_type = _ZONEINFO
DESCRIPTOR.message_types_by_name['ZoneInfo'] = _ZONEINFO
DESCRIPTOR.message_types_by_name['ZoneList'] = _ZONELIST
DESCRIPTOR.message_types_by_name['RoleID'] = _ROLEID
DESCRIPTOR.message_types_by_name['LogoutServer_Request'] = _LOGOUTSERVER_REQUEST
DESCRIPTOR.message_types_by_name['LogoutServer_Response'] = _LOGOUTSERVER_RESPONSE
DESCRIPTOR.message_types_by_name['AddNewName_Request'] = _ADDNEWNAME_REQUEST
DESCRIPTOR.message_types_by_name['AddNewName_Response'] = _ADDNEWNAME_RESPONSE
DESCRIPTOR.message_types_by_name['DeleteName_Request'] = _DELETENAME_REQUEST
DESCRIPTOR.message_types_by_name['DeleteName_Response'] = _DELETENAME_RESPONSE

class ZoneInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ZONEINFO

  # @@protoc_insertion_point(class_scope:ZoneInfo)

class ZoneList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ZONELIST

  # @@protoc_insertion_point(class_scope:ZoneList)

class RoleID(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROLEID

  # @@protoc_insertion_point(class_scope:RoleID)

class LogoutServer_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGOUTSERVER_REQUEST

  # @@protoc_insertion_point(class_scope:LogoutServer_Request)

class LogoutServer_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGOUTSERVER_RESPONSE

  # @@protoc_insertion_point(class_scope:LogoutServer_Response)

class AddNewName_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDNEWNAME_REQUEST

  # @@protoc_insertion_point(class_scope:AddNewName_Request)

class AddNewName_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDNEWNAME_RESPONSE

  # @@protoc_insertion_point(class_scope:AddNewName_Response)

class DeleteName_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETENAME_REQUEST

  # @@protoc_insertion_point(class_scope:DeleteName_Request)

class DeleteName_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETENAME_RESPONSE

  # @@protoc_insertion_point(class_scope:DeleteName_Response)


# @@protoc_insertion_point(module_scope)
