# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameProtocol.LOG.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameProtocol.LOG.proto',
  package='',
  serialized_pb='\n\x16GameProtocol.LOG.proto\"\x84\x01\n\nCreateRole\x12\x10\n\x08iEventID\x18\x01 \x01(\x03\x12\x0b\n\x03uin\x18\x02 \x01(\r\x12\x0c\n\x04time\x18\x03 \x01(\r\x12\x11\n\tiClientIP\x18\x04 \x01(\r\x12\x13\n\x0bstrRoleName\x18\x05 \x01(\t\x12\x0f\n\x07iGender\x18\x06 \x01(\r\x12\x10\n\x08iAppType\x18\x07 \x01(\r\"\x86\x01\n\nDeleteRole\x12\x10\n\x08iEventID\x18\x01 \x01(\x03\x12\x0b\n\x03uin\x18\x02 \x01(\r\x12\x0c\n\x04time\x18\x03 \x01(\r\x12\x11\n\tiClientIP\x18\x04 \x01(\r\x12\x13\n\x0bstrRoleName\x18\x05 \x01(\t\x12\x0f\n\x07iGender\x18\x06 \x01(\r\x12\x12\n\niRoleLevel\x18\x07 \x01(\r\"Q\n\tLogDetail\x12!\n\x0cstCreateRole\x18\x01 \x01(\x0b\x32\x0b.CreateRole\x12!\n\x0cstDeleteRole\x18\x02 \x01(\x0b\x32\x0b.DeleteRole\"2\n\x06LogPkg\x12\x0b\n\x03\x63md\x18\x01 \x01(\r\x12\x1b\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\n.LogDetail*4\n\x08LogMsgID\x12\x13\n\x0eLOG_CREATEROLE\x10\xe9\x07\x12\x13\n\x0eLOG_DELETEROLE\x10\xea\x07')

_LOGMSGID = _descriptor.EnumDescriptor(
  name='LogMsgID',
  full_name='LogMsgID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOG_CREATEROLE', index=0, number=1001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOG_DELETEROLE', index=1, number=1002,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=433,
  serialized_end=485,
)

LogMsgID = enum_type_wrapper.EnumTypeWrapper(_LOGMSGID)
LOG_CREATEROLE = 1001
LOG_DELETEROLE = 1002



_CREATEROLE = _descriptor.Descriptor(
  name='CreateRole',
  full_name='CreateRole',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iEventID', full_name='CreateRole.iEventID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uin', full_name='CreateRole.uin', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='CreateRole.time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iClientIP', full_name='CreateRole.iClientIP', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strRoleName', full_name='CreateRole.strRoleName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iGender', full_name='CreateRole.iGender', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iAppType', full_name='CreateRole.iAppType', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=159,
)


_DELETEROLE = _descriptor.Descriptor(
  name='DeleteRole',
  full_name='DeleteRole',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iEventID', full_name='DeleteRole.iEventID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uin', full_name='DeleteRole.uin', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='DeleteRole.time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iClientIP', full_name='DeleteRole.iClientIP', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strRoleName', full_name='DeleteRole.strRoleName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iGender', full_name='DeleteRole.iGender', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iRoleLevel', full_name='DeleteRole.iRoleLevel', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=162,
  serialized_end=296,
)


_LOGDETAIL = _descriptor.Descriptor(
  name='LogDetail',
  full_name='LogDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stCreateRole', full_name='LogDetail.stCreateRole', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stDeleteRole', full_name='LogDetail.stDeleteRole', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=298,
  serialized_end=379,
)


_LOGPKG = _descriptor.Descriptor(
  name='LogPkg',
  full_name='LogPkg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='LogPkg.cmd', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='details', full_name='LogPkg.details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=381,
  serialized_end=431,
)

_LOGDETAIL.fields_by_name['stCreateRole'].message_type = _CREATEROLE
_LOGDETAIL.fields_by_name['stDeleteRole'].message_type = _DELETEROLE
_LOGPKG.fields_by_name['details'].message_type = _LOGDETAIL
DESCRIPTOR.message_types_by_name['CreateRole'] = _CREATEROLE
DESCRIPTOR.message_types_by_name['DeleteRole'] = _DELETEROLE
DESCRIPTOR.message_types_by_name['LogDetail'] = _LOGDETAIL
DESCRIPTOR.message_types_by_name['LogPkg'] = _LOGPKG

class CreateRole(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEROLE

  # @@protoc_insertion_point(class_scope:CreateRole)

class DeleteRole(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEROLE

  # @@protoc_insertion_point(class_scope:DeleteRole)

class LogDetail(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGDETAIL

  # @@protoc_insertion_point(class_scope:LogDetail)

class LogPkg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGPKG

  # @@protoc_insertion_point(class_scope:LogPkg)


# @@protoc_insertion_point(module_scope)
